### ISSUE TITLE
`--save-model` does not include finetuned weights?

### ISSUE THREAD

**Issue by denkorzh** [VainF/TinyFusion#3]
https://github.com/VainF/TinyFusion/blob/ebf53a91eee0cf3b30e219307b98fe3b443a7fc9/prune_by_learning.py#L447

Hi, it seems to me that when `--save-model` argument is used, the `clean_state_dict` dictionary selected non-pruned blocks from the *original* checkpoint, and not the *finetuned* one. Is this behavior intended? Thank you in advance.

**Comment by VainF** [comment]
Hi @denkorzh, that's an expected behavior. The fine-tuned parameters are not suitable for standard fine-tuning.

**Comment by denkorzh** [comment]
Thank you for your explanation!
